/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param email 
 * @param password 
 * @param username 
 * @param displayName 
 */
@Serializable

data class CreateUserDto (

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "password")
    val password: kotlin.String,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null

) {


}

