/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One change in the drive delta. `kind` discriminates the shape.
 *
 * @param kind 
 * @param changeSeq 
 * @param id 
 * @param name 
 * @param folderId 
 * @param parentId 
 * @param path Materialized folder path (folders).
 * @param etag Content hash (files).
 * @param propertySize 
 * @param mimeType 
 * @param trashed 
 * @param target Deleted item kind.
 * @param deletedAt 
 */
@Serializable

data class DriveChange (

    @SerialName(value = "kind")
    val kind: DriveChange.Kind,

    @SerialName(value = "change_seq")
    val changeSeq: kotlin.Long,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @Contextual @SerialName(value = "folder_id")
    val folderId: java.util.UUID? = null,

    @Contextual @SerialName(value = "parent_id")
    val parentId: java.util.UUID? = null,

    /* Materialized folder path (folders). */
    @SerialName(value = "path")
    val path: kotlin.String? = null,

    /* Content hash (files). */
    @SerialName(value = "etag")
    val etag: kotlin.String? = null,

    @SerialName(value = "size")
    val propertySize: kotlin.Long? = null,

    @SerialName(value = "mime_type")
    val mimeType: kotlin.String? = null,

    @SerialName(value = "trashed")
    val trashed: kotlin.Boolean? = null,

    /* Deleted item kind. */
    @SerialName(value = "target")
    val target: DriveChange.Target? = null,

    @Contextual @SerialName(value = "deleted_at")
    val deletedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: file,folder,deleted
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "file") file("file"),
        @SerialName(value = "folder") folder("folder"),
        @SerialName(value = "deleted") deleted("deleted");
    }
    /**
     * Deleted item kind.
     *
     * Values: file,folder
     */
    @Serializable
    enum class Target(val value: kotlin.String) {
        @SerialName(value = "file") file("file"),
        @SerialName(value = "folder") folder("folder");
    }

}

