/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import com.kubuno.api.models.DriveChange

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param changes 
 * @param cursor 
 * @param hasMore 
 */
@Serializable

data class DriveDelta (

    @SerialName(value = "changes")
    val changes: kotlin.collections.List<DriveChange>,

    @SerialName(value = "cursor")
    val cursor: kotlin.Long,

    @SerialName(value = "has_more")
    val hasMore: kotlin.Boolean

) {


}

