/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param login Email ou nom d'utilisateur.
 * @param password 
 * @param clientType 'web' (default) keeps the HttpOnly cookie. 'native'/'desktop' receive the refresh token in the JSON body (no cookie) so non-browser clients can store it in the OS keychain and refresh without a cookie jar.
 * @param deviceName 
 * @param deviceType 
 */
@Serializable

data class LoginDto (

    /* Email ou nom d'utilisateur. */
    @SerialName(value = "login")
    val login: kotlin.String,

    @SerialName(value = "password")
    val password: kotlin.String,

    /* 'web' (default) keeps the HttpOnly cookie. 'native'/'desktop' receive the refresh token in the JSON body (no cookie) so non-browser clients can store it in the OS keychain and refresh without a cookie jar. */
    @SerialName(value = "client_type")
    val clientType: kotlin.String? = null,

    @SerialName(value = "device_name")
    val deviceName: kotlin.String? = null,

    @SerialName(value = "device_type")
    val deviceType: kotlin.String? = null

) {


}

