/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import com.kubuno.api.models.User

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Token response for native/desktop clients. The raw refresh token is returned in the body (never logged) and rotated on every `/auth/refresh`.  `Debug` is intentionally NOT derived: the refresh token must never reach the logs through a stray `{:?}`.
 *
 * @param accessToken 
 * @param refreshExpiresAt 
 * @param refreshToken 
 * @param user 
 */
@Serializable

data class NativeTokenResponse (

    @SerialName(value = "access_token")
    val accessToken: kotlin.String,

    @Contextual @SerialName(value = "refresh_expires_at")
    val refreshExpiresAt: java.time.OffsetDateTime,

    @SerialName(value = "refresh_token")
    val refreshToken: kotlin.String,

    @SerialName(value = "user")
    val user: User

) {


}

