/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param expiresAt 
 * @param id 
 * @param lastUsedAt 
 * @param userId 
 * @param clientType How the session was opened: 'web' | 'native' | 'desktop' | 'api'.
 * @param deviceName 
 * @param deviceType 
 * @param familyId Root of the rotation chain (all refresh tokens issued from one device login).
 * @param ipAddress 
 * @param revokeReason 
 * @param revokedAt 
 * @param userAgent 
 */
@Serializable

data class RefreshToken (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "last_used_at")
    val lastUsedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "user_id")
    val userId: java.util.UUID,

    /* How the session was opened: 'web' | 'native' | 'desktop' | 'api'. */
    @SerialName(value = "client_type")
    val clientType: kotlin.String? = null,

    @SerialName(value = "device_name")
    val deviceName: kotlin.String? = null,

    @SerialName(value = "device_type")
    val deviceType: kotlin.String? = null,

    /* Root of the rotation chain (all refresh tokens issued from one device login). */
    @Contextual @SerialName(value = "family_id")
    val familyId: java.util.UUID? = null,

    @SerialName(value = "ip_address")
    val ipAddress: kotlin.String? = null,

    @SerialName(value = "revoke_reason")
    val revokeReason: kotlin.String? = null,

    @Contextual @SerialName(value = "revoked_at")
    val revokedAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "user_agent")
    val userAgent: kotlin.String? = null

) {


}

