/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param provider 
 * @param deviceToken Endpoint URL (unifiedpush) or push token.
 * @param appId 
 * @param locale 
 */
@Serializable

data class RegisterDeviceDto (

    @SerialName(value = "provider")
    val provider: RegisterDeviceDto.Provider,

    /* Endpoint URL (unifiedpush) or push token. */
    @SerialName(value = "device_token")
    val deviceToken: kotlin.String,

    @SerialName(value = "app_id")
    val appId: kotlin.String? = null,

    @SerialName(value = "locale")
    val locale: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: unifiedpush,apns,fcm
     */
    @Serializable
    enum class Provider(val value: kotlin.String) {
        @SerialName(value = "unifiedpush") unifiedpush("unifiedpush"),
        @SerialName(value = "apns") apns("apns"),
        @SerialName(value = "fcm") fcm("fcm");
    }

}

