/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enabled 
 * @param moduleId '*' = all modules.
 * @param eventType '*' = all events.
 */
@Serializable

data class SetPreferenceDto (

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    /* '*' = all modules. */
    @SerialName(value = "module_id")
    val moduleId: kotlin.String? = null,

    /* '*' = all events. */
    @SerialName(value = "event_type")
    val eventType: kotlin.String? = null

) {


}

