/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code 
 * @param totpSession 
 * @param clientType Idem qu'au login : 'native'/'desktop' reçoivent le refresh en JSON.
 */
@Serializable

data class TotpVerifyDto (

    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "totp_session")
    val totpSession: kotlin.String,

    /* Idem qu'au login : 'native'/'desktop' reçoivent le refresh en JSON. */
    @SerialName(value = "client_type")
    val clientType: kotlin.String? = null

) {


}

