/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param createdAt 
 * @param email 
 * @param emailVerified 
 * @param id 
 * @param isActive 
 * @param preferences 
 * @param quotaBytes 
 * @param role 
 * @param totpEnabled 
 * @param updatedAt 
 * @param usedBytes 
 * @param username 
 * @param avatarUrl 
 * @param displayName 
 * @param lastLoginAt 
 * @param oauthId 
 * @param oauthProvider 
 */
@Serializable

data class User (

    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "email_verified")
    val emailVerified: kotlin.Boolean,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "is_active")
    val isActive: kotlin.Boolean,

    @Contextual @SerialName(value = "preferences")
    val preferences: kotlin.Any?,

    @SerialName(value = "quota_bytes")
    val quotaBytes: kotlin.Long,

    @SerialName(value = "role")
    val role: kotlin.String,

    @SerialName(value = "totp_enabled")
    val totpEnabled: kotlin.Boolean,

    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @SerialName(value = "used_bytes")
    val usedBytes: kotlin.Long,

    @SerialName(value = "username")
    val username: kotlin.String,

    @SerialName(value = "avatar_url")
    val avatarUrl: kotlin.String? = null,

    @SerialName(value = "display_name")
    val displayName: kotlin.String? = null,

    @Contextual @SerialName(value = "last_login_at")
    val lastLoginAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "oauth_id")
    val oauthId: kotlin.String? = null,

    @SerialName(value = "oauth_provider")
    val oauthProvider: kotlin.String? = null

) {


}

