//
// ApiV1DriveFoldersPost200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiV1DriveFoldersPost200Response: Codable, JSONEncodable, Hashable {

    public var folder: DriveFolder?

    public init(folder: DriveFolder? = nil) {
        self.folder = folder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case folder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(folder, forKey: .folder)
    }
}

