//
// CreateFolderDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateFolderDto: Codable, JSONEncodable, Hashable {

    public var parentId: UUID?
    public var name: String

    public init(parentId: UUID? = nil, name: String) {
        self.parentId = parentId
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parentId = "parent_id"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encode(name, forKey: .name)
    }
}

