//
// DriveDelta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DriveDelta: Codable, JSONEncodable, Hashable {

    public var changes: [DriveChange]
    public var cursor: Int64
    public var hasMore: Bool

    public init(changes: [DriveChange], cursor: Int64, hasMore: Bool) {
        self.changes = changes
        self.cursor = cursor
        self.hasMore = hasMore
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case changes
        case cursor
        case hasMore = "has_more"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(changes, forKey: .changes)
        try container.encode(cursor, forKey: .cursor)
        try container.encode(hasMore, forKey: .hasMore)
    }
}

