//
// DriveFolder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DriveFolder: Codable, JSONEncodable, Hashable {

    public var id: UUID?
    public var name: String?
    public var parentId: UUID?
    public var path: String?

    public init(id: UUID? = nil, name: String? = nil, parentId: UUID? = nil, path: String? = nil) {
        self.id = id
        self.name = name
        self.parentId = parentId
        self.path = path
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case parentId = "parent_id"
        case path
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encodeIfPresent(path, forKey: .path)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DriveFolder: Identifiable {}
