//
// DriveChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One change in the drive delta. &#x60;kind&#x60; discriminates the shape. */
public struct DriveChange: Codable, JSONEncodable, Hashable {

    public enum Kind: String, Codable, CaseIterable {
        case file = "file"
        case folder = "folder"
        case deleted = "deleted"
    }
    public enum Target: String, Codable, CaseIterable {
        case file = "file"
        case folder = "folder"
    }
    public var kind: Kind
    public var id: UUID?
    public var name: String?
    public var folderId: UUID?
    public var parentId: UUID?
    /** Materialized folder path (folders). */
    public var path: String?
    /** Content hash (files). */
    public var etag: String?
    public var size: Int64?
    public var mimeType: String?
    public var trashed: Bool?
    /** Deleted item kind. */
    public var target: Target?
    public var deletedAt: Date?
    public var changeSeq: Int64

    public init(kind: Kind, id: UUID? = nil, name: String? = nil, folderId: UUID? = nil, parentId: UUID? = nil, path: String? = nil, etag: String? = nil, size: Int64? = nil, mimeType: String? = nil, trashed: Bool? = nil, target: Target? = nil, deletedAt: Date? = nil, changeSeq: Int64) {
        self.kind = kind
        self.id = id
        self.name = name
        self.folderId = folderId
        self.parentId = parentId
        self.path = path
        self.etag = etag
        self.size = size
        self.mimeType = mimeType
        self.trashed = trashed
        self.target = target
        self.deletedAt = deletedAt
        self.changeSeq = changeSeq
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case id
        case name
        case folderId = "folder_id"
        case parentId = "parent_id"
        case path
        case etag
        case size
        case mimeType = "mime_type"
        case trashed
        case target
        case deletedAt = "deleted_at"
        case changeSeq = "change_seq"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(folderId, forKey: .folderId)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(etag, forKey: .etag)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(mimeType, forKey: .mimeType)
        try container.encodeIfPresent(trashed, forKey: .trashed)
        try container.encodeIfPresent(target, forKey: .target)
        try container.encodeIfPresent(deletedAt, forKey: .deletedAt)
        try container.encode(changeSeq, forKey: .changeSeq)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension DriveChange: Identifiable {}
