//
// LoginDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginDto: Codable, JSONEncodable, Hashable {

    /** 'web' (default) keeps the HttpOnly cookie. 'native'/'desktop' receive the refresh token in the JSON body (no cookie) so non-browser clients can store it in the OS keychain and refresh without a cookie jar. */
    public var clientType: String?
    public var deviceName: String?
    public var deviceType: String?
    /** Email ou nom d'utilisateur. */
    public var login: String
    public var password: String

    public init(clientType: String? = nil, deviceName: String? = nil, deviceType: String? = nil, login: String, password: String) {
        self.clientType = clientType
        self.deviceName = deviceName
        self.deviceType = deviceType
        self.login = login
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientType = "client_type"
        case deviceName = "device_name"
        case deviceType = "device_type"
        case login
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientType, forKey: .clientType)
        try container.encodeIfPresent(deviceName, forKey: .deviceName)
        try container.encodeIfPresent(deviceType, forKey: .deviceType)
        try container.encode(login, forKey: .login)
        try container.encode(password, forKey: .password)
    }
}

