//
// NativeTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Token response for native/desktop clients. The raw refresh token is returned in the body (never logged) and rotated on every &#x60;/auth/refresh&#x60;.  &#x60;Debug&#x60; is intentionally NOT derived: the refresh token must never reach the logs through a stray &#x60;{:?}&#x60;. */
public struct NativeTokenResponse: Codable, JSONEncodable, Hashable {

    public var accessToken: String
    public var refreshExpiresAt: Date
    public var refreshToken: String
    public var user: User

    public init(accessToken: String, refreshExpiresAt: Date, refreshToken: String, user: User) {
        self.accessToken = accessToken
        self.refreshExpiresAt = refreshExpiresAt
        self.refreshToken = refreshToken
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
        case refreshExpiresAt = "refresh_expires_at"
        case refreshToken = "refresh_token"
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(refreshExpiresAt, forKey: .refreshExpiresAt)
        try container.encode(refreshToken, forKey: .refreshToken)
        try container.encode(user, forKey: .user)
    }
}

