//
// RefreshToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RefreshToken: Codable, JSONEncodable, Hashable {

    /** How the session was opened: 'web' | 'native' | 'desktop' | 'api'. */
    public var clientType: String?
    public var createdAt: Date
    public var deviceName: String?
    public var deviceType: String?
    public var expiresAt: Date
    /** Root of the rotation chain (all refresh tokens issued from one device login). */
    public var familyId: UUID?
    public var id: UUID
    public var ipAddress: String?
    public var lastUsedAt: Date
    public var revokeReason: String?
    public var revokedAt: Date?
    public var userAgent: String?
    public var userId: UUID

    public init(clientType: String? = nil, createdAt: Date, deviceName: String? = nil, deviceType: String? = nil, expiresAt: Date, familyId: UUID? = nil, id: UUID, ipAddress: String? = nil, lastUsedAt: Date, revokeReason: String? = nil, revokedAt: Date? = nil, userAgent: String? = nil, userId: UUID) {
        self.clientType = clientType
        self.createdAt = createdAt
        self.deviceName = deviceName
        self.deviceType = deviceType
        self.expiresAt = expiresAt
        self.familyId = familyId
        self.id = id
        self.ipAddress = ipAddress
        self.lastUsedAt = lastUsedAt
        self.revokeReason = revokeReason
        self.revokedAt = revokedAt
        self.userAgent = userAgent
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientType = "client_type"
        case createdAt = "created_at"
        case deviceName = "device_name"
        case deviceType = "device_type"
        case expiresAt = "expires_at"
        case familyId = "family_id"
        case id
        case ipAddress = "ip_address"
        case lastUsedAt = "last_used_at"
        case revokeReason = "revoke_reason"
        case revokedAt = "revoked_at"
        case userAgent = "user_agent"
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientType, forKey: .clientType)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(deviceName, forKey: .deviceName)
        try container.encodeIfPresent(deviceType, forKey: .deviceType)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(familyId, forKey: .familyId)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(ipAddress, forKey: .ipAddress)
        try container.encode(lastUsedAt, forKey: .lastUsedAt)
        try container.encodeIfPresent(revokeReason, forKey: .revokeReason)
        try container.encodeIfPresent(revokedAt, forKey: .revokedAt)
        try container.encodeIfPresent(userAgent, forKey: .userAgent)
        try container.encode(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RefreshToken: Identifiable {}
