//
// RegisterDeviceDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterDeviceDto: Codable, JSONEncodable, Hashable {

    public enum Provider: String, Codable, CaseIterable {
        case unifiedpush = "unifiedpush"
        case apns = "apns"
        case fcm = "fcm"
    }
    public var provider: Provider
    /** Endpoint URL (unifiedpush) or push token. */
    public var deviceToken: String
    public var appId: String?
    public var locale: String?

    public init(provider: Provider, deviceToken: String, appId: String? = nil, locale: String? = nil) {
        self.provider = provider
        self.deviceToken = deviceToken
        self.appId = appId
        self.locale = locale
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case provider
        case deviceToken = "device_token"
        case appId = "app_id"
        case locale
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(provider, forKey: .provider)
        try container.encode(deviceToken, forKey: .deviceToken)
        try container.encodeIfPresent(appId, forKey: .appId)
        try container.encodeIfPresent(locale, forKey: .locale)
    }
}

