//
// SetPreferenceDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SetPreferenceDto: Codable, JSONEncodable, Hashable {

    /** '*' = all modules. */
    public var moduleId: String?
    /** '*' = all events. */
    public var eventType: String?
    public var enabled: Bool

    public init(moduleId: String? = nil, eventType: String? = nil, enabled: Bool) {
        self.moduleId = moduleId
        self.eventType = eventType
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case moduleId = "module_id"
        case eventType = "event_type"
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(moduleId, forKey: .moduleId)
        try container.encodeIfPresent(eventType, forKey: .eventType)
        try container.encode(enabled, forKey: .enabled)
    }
}

