//
// TotpVerifyDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TotpVerifyDto: Codable, JSONEncodable, Hashable {

    /** Idem qu'au login : 'native'/'desktop' reçoivent le refresh en JSON. */
    public var clientType: String?
    public var code: String
    public var totpSession: String

    public init(clientType: String? = nil, code: String, totpSession: String) {
        self.clientType = clientType
        self.code = code
        self.totpSession = totpSession
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientType = "client_type"
        case code
        case totpSession = "totp_session"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clientType, forKey: .clientType)
        try container.encode(code, forKey: .code)
        try container.encode(totpSession, forKey: .totpSession)
    }
}

