//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct User: Codable, JSONEncodable, Hashable {

    public var avatarUrl: String?
    public var createdAt: Date
    public var displayName: String?
    public var email: String
    public var emailVerified: Bool
    public var id: UUID
    public var isActive: Bool
    public var lastLoginAt: Date?
    public var oauthId: String?
    public var oauthProvider: String?
    public var preferences: AnyCodable?
    public var quotaBytes: Int64
    public var role: String
    public var totpEnabled: Bool
    public var updatedAt: Date
    public var usedBytes: Int64
    public var username: String

    public init(avatarUrl: String? = nil, createdAt: Date, displayName: String? = nil, email: String, emailVerified: Bool, id: UUID, isActive: Bool, lastLoginAt: Date? = nil, oauthId: String? = nil, oauthProvider: String? = nil, preferences: AnyCodable?, quotaBytes: Int64, role: String, totpEnabled: Bool, updatedAt: Date, usedBytes: Int64, username: String) {
        self.avatarUrl = avatarUrl
        self.createdAt = createdAt
        self.displayName = displayName
        self.email = email
        self.emailVerified = emailVerified
        self.id = id
        self.isActive = isActive
        self.lastLoginAt = lastLoginAt
        self.oauthId = oauthId
        self.oauthProvider = oauthProvider
        self.preferences = preferences
        self.quotaBytes = quotaBytes
        self.role = role
        self.totpEnabled = totpEnabled
        self.updatedAt = updatedAt
        self.usedBytes = usedBytes
        self.username = username
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case avatarUrl = "avatar_url"
        case createdAt = "created_at"
        case displayName = "display_name"
        case email
        case emailVerified = "email_verified"
        case id
        case isActive = "is_active"
        case lastLoginAt = "last_login_at"
        case oauthId = "oauth_id"
        case oauthProvider = "oauth_provider"
        case preferences
        case quotaBytes = "quota_bytes"
        case role
        case totpEnabled = "totp_enabled"
        case updatedAt = "updated_at"
        case usedBytes = "used_bytes"
        case username
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(avatarUrl, forKey: .avatarUrl)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encode(email, forKey: .email)
        try container.encode(emailVerified, forKey: .emailVerified)
        try container.encode(id, forKey: .id)
        try container.encode(isActive, forKey: .isActive)
        try container.encodeIfPresent(lastLoginAt, forKey: .lastLoginAt)
        try container.encodeIfPresent(oauthId, forKey: .oauthId)
        try container.encodeIfPresent(oauthProvider, forKey: .oauthProvider)
        try container.encode(preferences, forKey: .preferences)
        try container.encode(quotaBytes, forKey: .quotaBytes)
        try container.encode(role, forKey: .role)
        try container.encode(totpEnabled, forKey: .totpEnabled)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(usedBytes, forKey: .usedBytes)
        try container.encode(username, forKey: .username)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension User: Identifiable {}
