/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.models.ApiV1DriveFoldersPost200Response
import com.kubuno.api.models.DriveFolder

class ApiV1DriveFoldersPost200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiV1DriveFoldersPost200Response
        //val modelInstance = ApiV1DriveFoldersPost200Response()

        // to test the property `folder`
        should("test folder") {
            // uncomment below to test the property
            //modelInstance.folder shouldBe ("TODO")
        }

    }
}
