/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.models.DriveDelta
import com.kubuno.api.models.DriveChange

class DriveDeltaTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DriveDelta
        //val modelInstance = DriveDelta()

        // to test the property `changes`
        should("test changes") {
            // uncomment below to test the property
            //modelInstance.changes shouldBe ("TODO")
        }

        // to test the property `cursor`
        should("test cursor") {
            // uncomment below to test the property
            //modelInstance.cursor shouldBe ("TODO")
        }

        // to test the property `hasMore`
        should("test hasMore") {
            // uncomment below to test the property
            //modelInstance.hasMore shouldBe ("TODO")
        }

    }
}
