/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.models.DriveChange

class DriveChangeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DriveChange
        //val modelInstance = DriveChange()

        // to test the property `kind`
        should("test kind") {
            // uncomment below to test the property
            //modelInstance.kind shouldBe ("TODO")
        }

        // to test the property `changeSeq`
        should("test changeSeq") {
            // uncomment below to test the property
            //modelInstance.changeSeq shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `folderId`
        should("test folderId") {
            // uncomment below to test the property
            //modelInstance.folderId shouldBe ("TODO")
        }

        // to test the property `parentId`
        should("test parentId") {
            // uncomment below to test the property
            //modelInstance.parentId shouldBe ("TODO")
        }

        // to test the property `path` - Materialized folder path (folders).
        should("test path") {
            // uncomment below to test the property
            //modelInstance.path shouldBe ("TODO")
        }

        // to test the property `etag` - Content hash (files).
        should("test etag") {
            // uncomment below to test the property
            //modelInstance.etag shouldBe ("TODO")
        }

        // to test the property `propertySize`
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `mimeType`
        should("test mimeType") {
            // uncomment below to test the property
            //modelInstance.mimeType shouldBe ("TODO")
        }

        // to test the property `trashed`
        should("test trashed") {
            // uncomment below to test the property
            //modelInstance.trashed shouldBe ("TODO")
        }

        // to test the property `target` - Deleted item kind.
        should("test target") {
            // uncomment below to test the property
            //modelInstance.target shouldBe ("TODO")
        }

        // to test the property `deletedAt`
        should("test deletedAt") {
            // uncomment below to test the property
            //modelInstance.deletedAt shouldBe ("TODO")
        }

    }
}
