/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.models.LoginDto

class LoginDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LoginDto
        //val modelInstance = LoginDto()

        // to test the property `login` - Email ou nom d'utilisateur.
        should("test login") {
            // uncomment below to test the property
            //modelInstance.login shouldBe ("TODO")
        }

        // to test the property `password`
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `clientType` - 'web' (default) keeps the HttpOnly cookie. 'native'/'desktop' receive the refresh token in the JSON body (no cookie) so non-browser clients can store it in the OS keychain and refresh without a cookie jar.
        should("test clientType") {
            // uncomment below to test the property
            //modelInstance.clientType shouldBe ("TODO")
        }

        // to test the property `deviceName`
        should("test deviceName") {
            // uncomment below to test the property
            //modelInstance.deviceName shouldBe ("TODO")
        }

        // to test the property `deviceType`
        should("test deviceType") {
            // uncomment below to test the property
            //modelInstance.deviceType shouldBe ("TODO")
        }

    }
}
