/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.models.RefreshToken

class RefreshTokenTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RefreshToken
        //val modelInstance = RefreshToken()

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `lastUsedAt`
        should("test lastUsedAt") {
            // uncomment below to test the property
            //modelInstance.lastUsedAt shouldBe ("TODO")
        }

        // to test the property `userId`
        should("test userId") {
            // uncomment below to test the property
            //modelInstance.userId shouldBe ("TODO")
        }

        // to test the property `clientType` - How the session was opened: 'web' | 'native' | 'desktop' | 'api'.
        should("test clientType") {
            // uncomment below to test the property
            //modelInstance.clientType shouldBe ("TODO")
        }

        // to test the property `deviceName`
        should("test deviceName") {
            // uncomment below to test the property
            //modelInstance.deviceName shouldBe ("TODO")
        }

        // to test the property `deviceType`
        should("test deviceType") {
            // uncomment below to test the property
            //modelInstance.deviceType shouldBe ("TODO")
        }

        // to test the property `familyId` - Root of the rotation chain (all refresh tokens issued from one device login).
        should("test familyId") {
            // uncomment below to test the property
            //modelInstance.familyId shouldBe ("TODO")
        }

        // to test the property `ipAddress`
        should("test ipAddress") {
            // uncomment below to test the property
            //modelInstance.ipAddress shouldBe ("TODO")
        }

        // to test the property `revokeReason`
        should("test revokeReason") {
            // uncomment below to test the property
            //modelInstance.revokeReason shouldBe ("TODO")
        }

        // to test the property `revokedAt`
        should("test revokedAt") {
            // uncomment below to test the property
            //modelInstance.revokedAt shouldBe ("TODO")
        }

        // to test the property `userAgent`
        should("test userAgent") {
            // uncomment below to test the property
            //modelInstance.userAgent shouldBe ("TODO")
        }

    }
}
