/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.models.RegisterDeviceDto

class RegisterDeviceDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RegisterDeviceDto
        //val modelInstance = RegisterDeviceDto()

        // to test the property `provider`
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `deviceToken` - Endpoint URL (unifiedpush) or push token.
        should("test deviceToken") {
            // uncomment below to test the property
            //modelInstance.deviceToken shouldBe ("TODO")
        }

        // to test the property `appId`
        should("test appId") {
            // uncomment below to test the property
            //modelInstance.appId shouldBe ("TODO")
        }

        // to test the property `locale`
        should("test locale") {
            // uncomment below to test the property
            //modelInstance.locale shouldBe ("TODO")
        }

    }
}
