/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.models.SetPreferenceDto

class SetPreferenceDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SetPreferenceDto
        //val modelInstance = SetPreferenceDto()

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `moduleId` - '*' = all modules.
        should("test moduleId") {
            // uncomment below to test the property
            //modelInstance.moduleId shouldBe ("TODO")
        }

        // to test the property `eventType` - '*' = all events.
        should("test eventType") {
            // uncomment below to test the property
            //modelInstance.eventType shouldBe ("TODO")
        }

    }
}
