/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.models.TotpVerifyDto

class TotpVerifyDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TotpVerifyDto
        //val modelInstance = TotpVerifyDto()

        // to test the property `code`
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `totpSession`
        should("test totpSession") {
            // uncomment below to test the property
            //modelInstance.totpSession shouldBe ("TODO")
        }

        // to test the property `clientType` - Idem qu'au login : 'native'/'desktop' reçoivent le refresh en JSON.
        should("test clientType") {
            // uncomment below to test the property
            //modelInstance.clientType shouldBe ("TODO")
        }

    }
}
