/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.models.User

class UserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of User
        //val modelInstance = User()

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `email`
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `emailVerified`
        should("test emailVerified") {
            // uncomment below to test the property
            //modelInstance.emailVerified shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `isActive`
        should("test isActive") {
            // uncomment below to test the property
            //modelInstance.isActive shouldBe ("TODO")
        }

        // to test the property `preferences`
        should("test preferences") {
            // uncomment below to test the property
            //modelInstance.preferences shouldBe ("TODO")
        }

        // to test the property `quotaBytes`
        should("test quotaBytes") {
            // uncomment below to test the property
            //modelInstance.quotaBytes shouldBe ("TODO")
        }

        // to test the property `role`
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `totpEnabled`
        should("test totpEnabled") {
            // uncomment below to test the property
            //modelInstance.totpEnabled shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `usedBytes`
        should("test usedBytes") {
            // uncomment below to test the property
            //modelInstance.usedBytes shouldBe ("TODO")
        }

        // to test the property `username`
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `avatarUrl`
        should("test avatarUrl") {
            // uncomment below to test the property
            //modelInstance.avatarUrl shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `lastLoginAt`
        should("test lastLoginAt") {
            // uncomment below to test the property
            //modelInstance.lastLoginAt shouldBe ("TODO")
        }

        // to test the property `oauthId`
        should("test oauthId") {
            // uncomment below to test the property
            //modelInstance.oauthId shouldBe ("TODO")
        }

        // to test the property `oauthProvider`
        should("test oauthProvider") {
            // uncomment below to test the property
            //modelInstance.oauthProvider shouldBe ("TODO")
        }

    }
}
