/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.kubuno.api.models.CreateUserDto
import com.kubuno.api.models.LoginDto
import com.kubuno.api.models.NativeTokenResponse
import com.kubuno.api.models.RefreshRequest
import com.kubuno.api.models.TotpVerifyDto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import com.kubuno.api.infrastructure.ApiClient
import com.kubuno.api.infrastructure.ApiResponse
import com.kubuno.api.infrastructure.ClientException
import com.kubuno.api.infrastructure.ClientError
import com.kubuno.api.infrastructure.ServerException
import com.kubuno.api.infrastructure.ServerError
import com.kubuno.api.infrastructure.MultiValueMap
import com.kubuno.api.infrastructure.PartConfig
import com.kubuno.api.infrastructure.RequestConfig
import com.kubuno.api.infrastructure.RequestMethod
import com.kubuno.api.infrastructure.ResponseType
import com.kubuno.api.infrastructure.Success
import com.kubuno.api.infrastructure.toMultiValue
import com.kubuno.api.infrastructure.Serializer

open class AuthApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/auth/login
     * 
     * 
     * @param loginDto 
     * @return NativeTokenResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun login(loginDto: LoginDto) : NativeTokenResponse {
        val localVarResponse = loginWithHttpInfo(loginDto = loginDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NativeTokenResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/auth/login
     * 
     * 
     * @param loginDto 
     * @return ApiResponse<NativeTokenResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun loginWithHttpInfo(loginDto: LoginDto) : ApiResponse<NativeTokenResponse?> {
        val localVariableConfig = loginRequestConfig(loginDto = loginDto)

        return request<LoginDto, NativeTokenResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation login
     *
     * @param loginDto 
     * @return RequestConfig
     */
    fun loginRequestConfig(loginDto: LoginDto) : RequestConfig<LoginDto> {
        val localVariableBody = loginDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/auth/login",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/auth/logout
     * 
     * 
     * @param refreshRequest Optionnel — clients natifs. Le web envoie le refresh via cookie.
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun logout(refreshRequest: RefreshRequest) : Unit {
        val localVarResponse = logoutWithHttpInfo(refreshRequest = refreshRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/auth/logout
     * 
     * 
     * @param refreshRequest Optionnel — clients natifs. Le web envoie le refresh via cookie.
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun logoutWithHttpInfo(refreshRequest: RefreshRequest) : ApiResponse<Unit?> {
        val localVariableConfig = logoutRequestConfig(refreshRequest = refreshRequest)

        return request<RefreshRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation logout
     *
     * @param refreshRequest Optionnel — clients natifs. Le web envoie le refresh via cookie.
     * @return RequestConfig
     */
    fun logoutRequestConfig(refreshRequest: RefreshRequest) : RequestConfig<RefreshRequest> {
        val localVariableBody = refreshRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/auth/logout",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/auth/refresh
     * 
     * 
     * @param refreshRequest Optionnel — clients natifs. Le web envoie le refresh via cookie.
     * @return NativeTokenResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun refresh(refreshRequest: RefreshRequest) : NativeTokenResponse {
        val localVarResponse = refreshWithHttpInfo(refreshRequest = refreshRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NativeTokenResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/auth/refresh
     * 
     * 
     * @param refreshRequest Optionnel — clients natifs. Le web envoie le refresh via cookie.
     * @return ApiResponse<NativeTokenResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun refreshWithHttpInfo(refreshRequest: RefreshRequest) : ApiResponse<NativeTokenResponse?> {
        val localVariableConfig = refreshRequestConfig(refreshRequest = refreshRequest)

        return request<RefreshRequest, NativeTokenResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation refresh
     *
     * @param refreshRequest Optionnel — clients natifs. Le web envoie le refresh via cookie.
     * @return RequestConfig
     */
    fun refreshRequestConfig(refreshRequest: RefreshRequest) : RequestConfig<RefreshRequest> {
        val localVariableBody = refreshRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/auth/refresh",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/auth/register
     * 
     * 
     * @param createUserDto 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun register(createUserDto: CreateUserDto) : Unit {
        val localVarResponse = registerWithHttpInfo(createUserDto = createUserDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/auth/register
     * 
     * 
     * @param createUserDto 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun registerWithHttpInfo(createUserDto: CreateUserDto) : ApiResponse<Unit?> {
        val localVariableConfig = registerRequestConfig(createUserDto = createUserDto)

        return request<CreateUserDto, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation register
     *
     * @param createUserDto 
     * @return RequestConfig
     */
    fun registerRequestConfig(createUserDto: CreateUserDto) : RequestConfig<CreateUserDto> {
        val localVariableBody = createUserDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/auth/register",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/auth/totp
     * 
     * 
     * @param totpVerifyDto 
     * @return NativeTokenResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun totpVerify(totpVerifyDto: TotpVerifyDto) : NativeTokenResponse {
        val localVarResponse = totpVerifyWithHttpInfo(totpVerifyDto = totpVerifyDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as NativeTokenResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/auth/totp
     * 
     * 
     * @param totpVerifyDto 
     * @return ApiResponse<NativeTokenResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun totpVerifyWithHttpInfo(totpVerifyDto: TotpVerifyDto) : ApiResponse<NativeTokenResponse?> {
        val localVariableConfig = totpVerifyRequestConfig(totpVerifyDto = totpVerifyDto)

        return request<TotpVerifyDto, NativeTokenResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation totpVerify
     *
     * @param totpVerifyDto 
     * @return RequestConfig
     */
    fun totpVerifyRequestConfig(totpVerifyDto: TotpVerifyDto) : RequestConfig<TotpVerifyDto> {
        val localVariableBody = totpVerifyDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/auth/totp",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
