/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.kubuno.api.models.DriveDelta

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import com.kubuno.api.infrastructure.ApiClient
import com.kubuno.api.infrastructure.ApiResponse
import com.kubuno.api.infrastructure.ClientException
import com.kubuno.api.infrastructure.ClientError
import com.kubuno.api.infrastructure.ServerException
import com.kubuno.api.infrastructure.ServerError
import com.kubuno.api.infrastructure.MultiValueMap
import com.kubuno.api.infrastructure.PartConfig
import com.kubuno.api.infrastructure.RequestConfig
import com.kubuno.api.infrastructure.RequestMethod
import com.kubuno.api.infrastructure.ResponseType
import com.kubuno.api.infrastructure.Success
import com.kubuno.api.infrastructure.toMultiValue
import com.kubuno.api.infrastructure.Serializer

open class DriveSyncApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * GET /api/v1/drive/sync/delta
     * Changes since a cursor (delta sync).
     * 
     * @param cursor Last change_seq seen (0 &#x3D; full snapshot). (optional, default to 0L)
     * @param limit  (optional, default to 500)
     * @return DriveDelta
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1DriveSyncDeltaGet(cursor: kotlin.Long? = 0L, limit: kotlin.Int? = 500) : DriveDelta {
        val localVarResponse = apiV1DriveSyncDeltaGetWithHttpInfo(cursor = cursor, limit = limit)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DriveDelta
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/drive/sync/delta
     * Changes since a cursor (delta sync).
     * 
     * @param cursor Last change_seq seen (0 &#x3D; full snapshot). (optional, default to 0L)
     * @param limit  (optional, default to 500)
     * @return ApiResponse<DriveDelta?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1DriveSyncDeltaGetWithHttpInfo(cursor: kotlin.Long?, limit: kotlin.Int?) : ApiResponse<DriveDelta?> {
        val localVariableConfig = apiV1DriveSyncDeltaGetRequestConfig(cursor = cursor, limit = limit)

        return request<Unit, DriveDelta>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1DriveSyncDeltaGet
     *
     * @param cursor Last change_seq seen (0 &#x3D; full snapshot). (optional, default to 0L)
     * @param limit  (optional, default to 500)
     * @return RequestConfig
     */
    fun apiV1DriveSyncDeltaGetRequestConfig(cursor: kotlin.Long?, limit: kotlin.Int?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (cursor != null) {
                    put("cursor", listOf(cursor.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/drive/sync/delta",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /api/v1/drive/sync/file/{id}/content
     * Replace a file&#39;s content (conflict-safe).
     * 
     * @param id 
     * @param body 
     * @param ifMatch Expected etag; mismatch returns 412 (conflict). (optional)
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1DriveSyncFileIdContentPut(id: java.util.UUID, body: java.io.File, ifMatch: kotlin.String? = null, idempotencyKey: kotlin.String? = null) : Unit {
        val localVarResponse = apiV1DriveSyncFileIdContentPutWithHttpInfo(id = id, body = body, ifMatch = ifMatch, idempotencyKey = idempotencyKey)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /api/v1/drive/sync/file/{id}/content
     * Replace a file&#39;s content (conflict-safe).
     * 
     * @param id 
     * @param body 
     * @param ifMatch Expected etag; mismatch returns 412 (conflict). (optional)
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1DriveSyncFileIdContentPutWithHttpInfo(id: java.util.UUID, body: java.io.File, ifMatch: kotlin.String?, idempotencyKey: kotlin.String?) : ApiResponse<Unit?> {
        val localVariableConfig = apiV1DriveSyncFileIdContentPutRequestConfig(id = id, body = body, ifMatch = ifMatch, idempotencyKey = idempotencyKey)

        return request<java.io.File, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1DriveSyncFileIdContentPut
     *
     * @param id 
     * @param body 
     * @param ifMatch Expected etag; mismatch returns 412 (conflict). (optional)
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @return RequestConfig
     */
    fun apiV1DriveSyncFileIdContentPutRequestConfig(id: java.util.UUID, body: java.io.File, ifMatch: kotlin.String?, idempotencyKey: kotlin.String?) : RequestConfig<java.io.File> {
        val localVariableBody = body
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        ifMatch?.apply { localVariableHeaders["If-Match"] = this.toString() }
        idempotencyKey?.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/octet-stream"
        
        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/api/v1/drive/sync/file/{id}/content".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
