/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.kubuno.api.models.ApiV1DriveFoldersPost200Response
import com.kubuno.api.models.CreateFolderDto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import com.kubuno.api.infrastructure.ApiClient
import com.kubuno.api.infrastructure.ApiResponse
import com.kubuno.api.infrastructure.ClientException
import com.kubuno.api.infrastructure.ClientError
import com.kubuno.api.infrastructure.ServerException
import com.kubuno.api.infrastructure.ServerError
import com.kubuno.api.infrastructure.MultiValueMap
import com.kubuno.api.infrastructure.PartConfig
import com.kubuno.api.infrastructure.RequestConfig
import com.kubuno.api.infrastructure.RequestMethod
import com.kubuno.api.infrastructure.ResponseType
import com.kubuno.api.infrastructure.Success
import com.kubuno.api.infrastructure.toMultiValue
import com.kubuno.api.infrastructure.Serializer

open class DriveApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/v1/drive/folders
     * Create a folder.
     * 
     * @param createFolderDto 
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @return ApiV1DriveFoldersPost200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1DriveFoldersPost(createFolderDto: CreateFolderDto, idempotencyKey: kotlin.String? = null) : ApiV1DriveFoldersPost200Response {
        val localVarResponse = apiV1DriveFoldersPostWithHttpInfo(createFolderDto = createFolderDto, idempotencyKey = idempotencyKey)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ApiV1DriveFoldersPost200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/drive/folders
     * Create a folder.
     * 
     * @param createFolderDto 
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @return ApiResponse<ApiV1DriveFoldersPost200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1DriveFoldersPostWithHttpInfo(createFolderDto: CreateFolderDto, idempotencyKey: kotlin.String?) : ApiResponse<ApiV1DriveFoldersPost200Response?> {
        val localVariableConfig = apiV1DriveFoldersPostRequestConfig(createFolderDto = createFolderDto, idempotencyKey = idempotencyKey)

        return request<CreateFolderDto, ApiV1DriveFoldersPost200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1DriveFoldersPost
     *
     * @param createFolderDto 
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @return RequestConfig
     */
    fun apiV1DriveFoldersPostRequestConfig(createFolderDto: CreateFolderDto, idempotencyKey: kotlin.String?) : RequestConfig<CreateFolderDto> {
        val localVariableBody = createFolderDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        idempotencyKey?.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/drive/folders",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/drive/{id}/download
     * Download a file&#39;s content.
     * 
     * @param id 
     * @return java.io.File
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1DriveIdDownloadGet(id: java.util.UUID) : java.io.File {
        val localVarResponse = apiV1DriveIdDownloadGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as java.io.File
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/drive/{id}/download
     * Download a file&#39;s content.
     * 
     * @param id 
     * @return ApiResponse<java.io.File?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1DriveIdDownloadGetWithHttpInfo(id: java.util.UUID) : ApiResponse<java.io.File?> {
        val localVariableConfig = apiV1DriveIdDownloadGetRequestConfig(id = id)

        return request<Unit, java.io.File>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1DriveIdDownloadGet
     *
     * @param id 
     * @return RequestConfig
     */
    fun apiV1DriveIdDownloadGetRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/octet-stream"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/drive/{id}/download".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/drive/{id}/trash
     * Move a file to trash.
     * 
     * @param id 
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1DriveIdTrashPost(id: java.util.UUID, idempotencyKey: kotlin.String? = null) : Unit {
        val localVarResponse = apiV1DriveIdTrashPostWithHttpInfo(id = id, idempotencyKey = idempotencyKey)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/drive/{id}/trash
     * Move a file to trash.
     * 
     * @param id 
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1DriveIdTrashPostWithHttpInfo(id: java.util.UUID, idempotencyKey: kotlin.String?) : ApiResponse<Unit?> {
        val localVariableConfig = apiV1DriveIdTrashPostRequestConfig(id = id, idempotencyKey = idempotencyKey)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1DriveIdTrashPost
     *
     * @param id 
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @return RequestConfig
     */
    fun apiV1DriveIdTrashPostRequestConfig(id: java.util.UUID, idempotencyKey: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        idempotencyKey?.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/drive/{id}/trash".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/drive/upload
     * Upload a new file (multipart).
     * 
     * @param file 
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @param folderId  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1DriveUploadPost(file: java.io.File, idempotencyKey: kotlin.String? = null, folderId: java.util.UUID? = null) : Unit {
        val localVarResponse = apiV1DriveUploadPostWithHttpInfo(file = file, idempotencyKey = idempotencyKey, folderId = folderId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/drive/upload
     * Upload a new file (multipart).
     * 
     * @param file 
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @param folderId  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1DriveUploadPostWithHttpInfo(file: java.io.File, idempotencyKey: kotlin.String?, folderId: java.util.UUID?) : ApiResponse<Unit?> {
        val localVariableConfig = apiV1DriveUploadPostRequestConfig(file = file, idempotencyKey = idempotencyKey, folderId = folderId)

        return request<Map<String, PartConfig<*>>, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1DriveUploadPost
     *
     * @param file 
     * @param idempotencyKey Stable key so a replayed mutation is not applied twice. (optional)
     * @param folderId  (optional)
     * @return RequestConfig
     */
    fun apiV1DriveUploadPostRequestConfig(file: java.io.File, idempotencyKey: kotlin.String?, folderId: java.util.UUID?) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "file" to PartConfig(body = file, headers = mutableMapOf()),
            "folder_id" to PartConfig(body = folderId, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        idempotencyKey?.apply { localVariableHeaders["Idempotency-Key"] = this.toString() }
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/drive/upload",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
