/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.kubuno.api.models.RegisterDeviceDto
import com.kubuno.api.models.SetPreferenceDto

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import com.kubuno.api.infrastructure.ApiClient
import com.kubuno.api.infrastructure.ApiResponse
import com.kubuno.api.infrastructure.ClientException
import com.kubuno.api.infrastructure.ClientError
import com.kubuno.api.infrastructure.ServerException
import com.kubuno.api.infrastructure.ServerError
import com.kubuno.api.infrastructure.MultiValueMap
import com.kubuno.api.infrastructure.PartConfig
import com.kubuno.api.infrastructure.RequestConfig
import com.kubuno.api.infrastructure.RequestMethod
import com.kubuno.api.infrastructure.ResponseType
import com.kubuno.api.infrastructure.Success
import com.kubuno.api.infrastructure.toMultiValue
import com.kubuno.api.infrastructure.Serializer

open class PushApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * DELETE /api/v1/me/push/devices/{id}
     * Unregister a push device.
     * 
     * @param id 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1MePushDevicesIdDelete(id: java.util.UUID) : Unit {
        val localVarResponse = apiV1MePushDevicesIdDeleteWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /api/v1/me/push/devices/{id}
     * Unregister a push device.
     * 
     * @param id 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1MePushDevicesIdDeleteWithHttpInfo(id: java.util.UUID) : ApiResponse<Unit?> {
        val localVariableConfig = apiV1MePushDevicesIdDeleteRequestConfig(id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1MePushDevicesIdDelete
     *
     * @param id 
     * @return RequestConfig
     */
    fun apiV1MePushDevicesIdDeleteRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/me/push/devices/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/me/push/devices
     * Register (or refresh) a push device.
     * 
     * @param registerDeviceDto 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1MePushDevicesPost(registerDeviceDto: RegisterDeviceDto) : Unit {
        val localVarResponse = apiV1MePushDevicesPostWithHttpInfo(registerDeviceDto = registerDeviceDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/me/push/devices
     * Register (or refresh) a push device.
     * 
     * @param registerDeviceDto 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1MePushDevicesPostWithHttpInfo(registerDeviceDto: RegisterDeviceDto) : ApiResponse<Unit?> {
        val localVariableConfig = apiV1MePushDevicesPostRequestConfig(registerDeviceDto = registerDeviceDto)

        return request<RegisterDeviceDto, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1MePushDevicesPost
     *
     * @param registerDeviceDto 
     * @return RequestConfig
     */
    fun apiV1MePushDevicesPostRequestConfig(registerDeviceDto: RegisterDeviceDto) : RequestConfig<RegisterDeviceDto> {
        val localVariableBody = registerDeviceDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/me/push/devices",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/me/push/preferences
     * List push opt-out preferences.
     * 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1MePushPreferencesGet() : Unit {
        val localVarResponse = apiV1MePushPreferencesGetWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/me/push/preferences
     * List push opt-out preferences.
     * 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1MePushPreferencesGetWithHttpInfo() : ApiResponse<Unit?> {
        val localVariableConfig = apiV1MePushPreferencesGetRequestConfig()

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1MePushPreferencesGet
     *
     * @return RequestConfig
     */
    fun apiV1MePushPreferencesGetRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/me/push/preferences",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/v1/me/push/preferences
     * Upsert one push preference.
     * 
     * @param setPreferenceDto 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun apiV1MePushPreferencesPatch(setPreferenceDto: SetPreferenceDto) : Unit {
        val localVarResponse = apiV1MePushPreferencesPatchWithHttpInfo(setPreferenceDto = setPreferenceDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/v1/me/push/preferences
     * Upsert one push preference.
     * 
     * @param setPreferenceDto 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun apiV1MePushPreferencesPatchWithHttpInfo(setPreferenceDto: SetPreferenceDto) : ApiResponse<Unit?> {
        val localVariableConfig = apiV1MePushPreferencesPatchRequestConfig(setPreferenceDto = setPreferenceDto)

        return request<SetPreferenceDto, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation apiV1MePushPreferencesPatch
     *
     * @param setPreferenceDto 
     * @return RequestConfig
     */
    fun apiV1MePushPreferencesPatchRequestConfig(setPreferenceDto: SetPreferenceDto) : RequestConfig<SetPreferenceDto> {
        val localVariableBody = setPreferenceDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/v1/me/push/preferences",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
