//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AuthAPI {

    /**

     - parameter loginDto: (body)  
     - returns: NativeTokenResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func login(loginDto: LoginDto) async throws -> NativeTokenResponse {
        return try await loginWithRequestBuilder(loginDto: loginDto).execute().body
    }

    /**
     - POST /api/v1/auth/login
     - parameter loginDto: (body)  
     - returns: RequestBuilder<NativeTokenResponse> 
     */
    open class func loginWithRequestBuilder(loginDto: LoginDto) -> RequestBuilder<NativeTokenResponse> {
        let localVariablePath = "/api/v1/auth/login"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: loginDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NativeTokenResponse>.Type = KubunoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter refreshRequest: (body) Optionnel — clients natifs. Le web envoie le refresh via cookie. 
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func logout(refreshRequest: RefreshRequest) async throws {
        return try await logoutWithRequestBuilder(refreshRequest: refreshRequest).execute().body
    }

    /**
     - POST /api/v1/auth/logout
     - parameter refreshRequest: (body) Optionnel — clients natifs. Le web envoie le refresh via cookie. 
     - returns: RequestBuilder<Void> 
     */
    open class func logoutWithRequestBuilder(refreshRequest: RefreshRequest) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/auth/logout"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: refreshRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = KubunoAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter refreshRequest: (body) Optionnel — clients natifs. Le web envoie le refresh via cookie. 
     - returns: NativeTokenResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func refresh(refreshRequest: RefreshRequest) async throws -> NativeTokenResponse {
        return try await refreshWithRequestBuilder(refreshRequest: refreshRequest).execute().body
    }

    /**
     - POST /api/v1/auth/refresh
     - parameter refreshRequest: (body) Optionnel — clients natifs. Le web envoie le refresh via cookie. 
     - returns: RequestBuilder<NativeTokenResponse> 
     */
    open class func refreshWithRequestBuilder(refreshRequest: RefreshRequest) -> RequestBuilder<NativeTokenResponse> {
        let localVariablePath = "/api/v1/auth/refresh"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: refreshRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NativeTokenResponse>.Type = KubunoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter createUserDto: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func register(createUserDto: CreateUserDto) async throws {
        return try await registerWithRequestBuilder(createUserDto: createUserDto).execute().body
    }

    /**
     - POST /api/v1/auth/register
     - parameter createUserDto: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func registerWithRequestBuilder(createUserDto: CreateUserDto) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/auth/register"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createUserDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = KubunoAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter totpVerifyDto: (body)  
     - returns: NativeTokenResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func totpVerify(totpVerifyDto: TotpVerifyDto) async throws -> NativeTokenResponse {
        return try await totpVerifyWithRequestBuilder(totpVerifyDto: totpVerifyDto).execute().body
    }

    /**
     - POST /api/v1/auth/totp
     - parameter totpVerifyDto: (body)  
     - returns: RequestBuilder<NativeTokenResponse> 
     */
    open class func totpVerifyWithRequestBuilder(totpVerifyDto: TotpVerifyDto) -> RequestBuilder<NativeTokenResponse> {
        let localVariablePath = "/api/v1/auth/totp"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: totpVerifyDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<NativeTokenResponse>.Type = KubunoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
