//
// DriveSyncAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DriveSyncAPI {

    /**
     Changes since a cursor (delta sync).
     
     - parameter cursor: (query) Last change_seq seen (0 &#x3D; full snapshot). (optional, default to 0)
     - parameter limit: (query)  (optional, default to 500)
     - returns: DriveDelta
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1DriveSyncDeltaGet(cursor: Int64? = nil, limit: Int? = nil) async throws -> DriveDelta {
        return try await apiV1DriveSyncDeltaGetWithRequestBuilder(cursor: cursor, limit: limit).execute().body
    }

    /**
     Changes since a cursor (delta sync).
     - GET /api/v1/drive/sync/delta
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter cursor: (query) Last change_seq seen (0 &#x3D; full snapshot). (optional, default to 0)
     - parameter limit: (query)  (optional, default to 500)
     - returns: RequestBuilder<DriveDelta> 
     */
    open class func apiV1DriveSyncDeltaGetWithRequestBuilder(cursor: Int64? = nil, limit: Int? = nil) -> RequestBuilder<DriveDelta> {
        let localVariablePath = "/api/v1/drive/sync/delta"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "cursor": (wrappedValue: cursor?.encodeToJSON(), isExplode: true),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<DriveDelta>.Type = KubunoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Replace a file's content (conflict-safe).
     
     - parameter id: (path)  
     - parameter body: (body)  
     - parameter ifMatch: (header) Expected etag; mismatch returns 412 (conflict). (optional)
     - parameter idempotencyKey: (header) Stable key so a replayed mutation is not applied twice. (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1DriveSyncFileIdContentPut(id: UUID, body: URL, ifMatch: String? = nil, idempotencyKey: String? = nil) async throws {
        return try await apiV1DriveSyncFileIdContentPutWithRequestBuilder(id: id, body: body, ifMatch: ifMatch, idempotencyKey: idempotencyKey).execute().body
    }

    /**
     Replace a file's content (conflict-safe).
     - PUT /api/v1/drive/sync/file/{id}/content
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter id: (path)  
     - parameter body: (body)  
     - parameter ifMatch: (header) Expected etag; mismatch returns 412 (conflict). (optional)
     - parameter idempotencyKey: (header) Stable key so a replayed mutation is not applied twice. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1DriveSyncFileIdContentPutWithRequestBuilder(id: UUID, body: URL, ifMatch: String? = nil, idempotencyKey: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/drive/sync/file/{id}/content"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters = ["body": body]

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/octet-stream",
            "If-Match": ifMatch?.encodeToJSON(),
            "Idempotency-Key": idempotencyKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = KubunoAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
