//
// DriveAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DriveAPI {

    /**
     Create a folder.
     
     - parameter createFolderDto: (body)  
     - parameter idempotencyKey: (header) Stable key so a replayed mutation is not applied twice. (optional)
     - returns: ApiV1DriveFoldersPost200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1DriveFoldersPost(createFolderDto: CreateFolderDto, idempotencyKey: String? = nil) async throws -> ApiV1DriveFoldersPost200Response {
        return try await apiV1DriveFoldersPostWithRequestBuilder(createFolderDto: createFolderDto, idempotencyKey: idempotencyKey).execute().body
    }

    /**
     Create a folder.
     - POST /api/v1/drive/folders
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter createFolderDto: (body)  
     - parameter idempotencyKey: (header) Stable key so a replayed mutation is not applied twice. (optional)
     - returns: RequestBuilder<ApiV1DriveFoldersPost200Response> 
     */
    open class func apiV1DriveFoldersPostWithRequestBuilder(createFolderDto: CreateFolderDto, idempotencyKey: String? = nil) -> RequestBuilder<ApiV1DriveFoldersPost200Response> {
        let localVariablePath = "/api/v1/drive/folders"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createFolderDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiV1DriveFoldersPost200Response>.Type = KubunoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Download a file's content.
     
     - parameter id: (path)  
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1DriveIdDownloadGet(id: UUID) async throws -> URL {
        return try await apiV1DriveIdDownloadGetWithRequestBuilder(id: id).execute().body
    }

    /**
     Download a file's content.
     - GET /api/v1/drive/{id}/download
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter id: (path)  
     - returns: RequestBuilder<URL> 
     */
    open class func apiV1DriveIdDownloadGetWithRequestBuilder(id: UUID) -> RequestBuilder<URL> {
        var localVariablePath = "/api/v1/drive/{id}/download"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = KubunoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Move a file to trash.
     
     - parameter id: (path)  
     - parameter idempotencyKey: (header) Stable key so a replayed mutation is not applied twice. (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1DriveIdTrashPost(id: UUID, idempotencyKey: String? = nil) async throws {
        return try await apiV1DriveIdTrashPostWithRequestBuilder(id: id, idempotencyKey: idempotencyKey).execute().body
    }

    /**
     Move a file to trash.
     - POST /api/v1/drive/{id}/trash
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter id: (path)  
     - parameter idempotencyKey: (header) Stable key so a replayed mutation is not applied twice. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1DriveIdTrashPostWithRequestBuilder(id: UUID, idempotencyKey: String? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/drive/{id}/trash"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Idempotency-Key": idempotencyKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = KubunoAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upload a new file (multipart).
     
     - parameter file: (form)  
     - parameter idempotencyKey: (header) Stable key so a replayed mutation is not applied twice. (optional)
     - parameter folderId: (form)  (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1DriveUploadPost(file: URL, idempotencyKey: String? = nil, folderId: UUID? = nil) async throws {
        return try await apiV1DriveUploadPostWithRequestBuilder(file: file, idempotencyKey: idempotencyKey, folderId: folderId).execute().body
    }

    /**
     Upload a new file (multipart).
     - POST /api/v1/drive/upload
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter file: (form)  
     - parameter idempotencyKey: (header) Stable key so a replayed mutation is not applied twice. (optional)
     - parameter folderId: (form)  (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1DriveUploadPostWithRequestBuilder(file: URL, idempotencyKey: String? = nil, folderId: UUID? = nil) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/drive/upload"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file.encodeToJSON(),
            "folder_id": folderId?.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
            "Idempotency-Key": idempotencyKey?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = KubunoAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
