//
// MeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MeAPI {

    /**

     - returns: User
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMe() async throws -> User {
        return try await getMeWithRequestBuilder().execute().body
    }

    /**
     - GET /api/v1/me
     - Bearer Token:
       - type: http
       - name: bearer
     - returns: RequestBuilder<User> 
     */
    open class func getMeWithRequestBuilder() -> RequestBuilder<User> {
        let localVariablePath = "/api/v1/me"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<User>.Type = KubunoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - returns: [RefreshToken]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listSessions() async throws -> [RefreshToken] {
        return try await listSessionsWithRequestBuilder().execute().body
    }

    /**
     - GET /api/v1/me/sessions
     - Bearer Token:
       - type: http
       - name: bearer
     - returns: RequestBuilder<[RefreshToken]> 
     */
    open class func listSessionsWithRequestBuilder() -> RequestBuilder<[RefreshToken]> {
        let localVariablePath = "/api/v1/me/sessions"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[RefreshToken]>.Type = KubunoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
