//
// PushAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PushAPI {

    /**
     Unregister a push device.
     
     - parameter id: (path)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1MePushDevicesIdDelete(id: UUID) async throws {
        return try await apiV1MePushDevicesIdDeleteWithRequestBuilder(id: id).execute().body
    }

    /**
     Unregister a push device.
     - DELETE /api/v1/me/push/devices/{id}
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter id: (path)  
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1MePushDevicesIdDeleteWithRequestBuilder(id: UUID) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/me/push/devices/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = KubunoAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Register (or refresh) a push device.
     
     - parameter registerDeviceDto: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1MePushDevicesPost(registerDeviceDto: RegisterDeviceDto) async throws {
        return try await apiV1MePushDevicesPostWithRequestBuilder(registerDeviceDto: registerDeviceDto).execute().body
    }

    /**
     Register (or refresh) a push device.
     - POST /api/v1/me/push/devices
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter registerDeviceDto: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1MePushDevicesPostWithRequestBuilder(registerDeviceDto: RegisterDeviceDto) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/me/push/devices"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: registerDeviceDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = KubunoAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List push opt-out preferences.
     
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1MePushPreferencesGet() async throws {
        return try await apiV1MePushPreferencesGetWithRequestBuilder().execute().body
    }

    /**
     List push opt-out preferences.
     - GET /api/v1/me/push/preferences
     - Bearer Token:
       - type: http
       - name: bearer
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1MePushPreferencesGetWithRequestBuilder() -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/me/push/preferences"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = KubunoAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upsert one push preference.
     
     - parameter setPreferenceDto: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1MePushPreferencesPatch(setPreferenceDto: SetPreferenceDto) async throws {
        return try await apiV1MePushPreferencesPatchWithRequestBuilder(setPreferenceDto: setPreferenceDto).execute().body
    }

    /**
     Upsert one push preference.
     - PATCH /api/v1/me/push/preferences
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter setPreferenceDto: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1MePushPreferencesPatchWithRequestBuilder(setPreferenceDto: SetPreferenceDto) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/me/push/preferences"
        let localVariableURLString = KubunoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: setPreferenceDto)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = KubunoAPIAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
