/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.apis.AuthApi
import com.kubuno.api.models.CreateUserDto
import com.kubuno.api.models.LoginDto
import com.kubuno.api.models.NativeTokenResponse
import com.kubuno.api.models.RefreshRequest
import com.kubuno.api.models.TotpVerifyDto

class AuthApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthApi
        //val apiInstance = AuthApi()

        // to test login
        should("test login") {
            // uncomment below to test login
            //val loginDto : LoginDto =  // LoginDto | 
            //val result : NativeTokenResponse = apiInstance.login(loginDto)
            //result shouldBe ("TODO")
        }

        // to test logout
        should("test logout") {
            // uncomment below to test logout
            //val refreshRequest : RefreshRequest =  // RefreshRequest | Optionnel — clients natifs. Le web envoie le refresh via cookie.
            //apiInstance.logout(refreshRequest)
        }

        // to test refresh
        should("test refresh") {
            // uncomment below to test refresh
            //val refreshRequest : RefreshRequest =  // RefreshRequest | Optionnel — clients natifs. Le web envoie le refresh via cookie.
            //val result : NativeTokenResponse = apiInstance.refresh(refreshRequest)
            //result shouldBe ("TODO")
        }

        // to test register
        should("test register") {
            // uncomment below to test register
            //val createUserDto : CreateUserDto =  // CreateUserDto | 
            //apiInstance.register(createUserDto)
        }

        // to test totpVerify
        should("test totpVerify") {
            // uncomment below to test totpVerify
            //val totpVerifyDto : TotpVerifyDto =  // TotpVerifyDto | 
            //val result : NativeTokenResponse = apiInstance.totpVerify(totpVerifyDto)
            //result shouldBe ("TODO")
        }

    }
}
