/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.apis.DriveSyncApi
import com.kubuno.api.models.DriveDelta

class DriveSyncApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DriveSyncApi
        //val apiInstance = DriveSyncApi()

        // to test apiV1DriveSyncDeltaGet
        should("test apiV1DriveSyncDeltaGet") {
            // uncomment below to test apiV1DriveSyncDeltaGet
            //val cursor : kotlin.Long = 789 // kotlin.Long | Last change_seq seen (0 = full snapshot).
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : DriveDelta = apiInstance.apiV1DriveSyncDeltaGet(cursor, limit)
            //result shouldBe ("TODO")
        }

        // to test apiV1DriveSyncFileIdContentPut
        should("test apiV1DriveSyncFileIdContentPut") {
            // uncomment below to test apiV1DriveSyncFileIdContentPut
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val body : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val ifMatch : kotlin.String = ifMatch_example // kotlin.String | Expected etag; mismatch returns 412 (conflict).
            //val idempotencyKey : kotlin.String = idempotencyKey_example // kotlin.String | Stable key so a replayed mutation is not applied twice.
            //apiInstance.apiV1DriveSyncFileIdContentPut(id, body, ifMatch, idempotencyKey)
        }

    }
}
