/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.apis.DriveApi
import com.kubuno.api.models.ApiV1DriveFoldersPost200Response
import com.kubuno.api.models.CreateFolderDto

class DriveApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DriveApi
        //val apiInstance = DriveApi()

        // to test apiV1DriveFoldersPost
        should("test apiV1DriveFoldersPost") {
            // uncomment below to test apiV1DriveFoldersPost
            //val createFolderDto : CreateFolderDto =  // CreateFolderDto | 
            //val idempotencyKey : kotlin.String = idempotencyKey_example // kotlin.String | Stable key so a replayed mutation is not applied twice.
            //val result : ApiV1DriveFoldersPost200Response = apiInstance.apiV1DriveFoldersPost(createFolderDto, idempotencyKey)
            //result shouldBe ("TODO")
        }

        // to test apiV1DriveIdDownloadGet
        should("test apiV1DriveIdDownloadGet") {
            // uncomment below to test apiV1DriveIdDownloadGet
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val result : java.io.File = apiInstance.apiV1DriveIdDownloadGet(id)
            //result shouldBe ("TODO")
        }

        // to test apiV1DriveIdTrashPost
        should("test apiV1DriveIdTrashPost") {
            // uncomment below to test apiV1DriveIdTrashPost
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //val idempotencyKey : kotlin.String = idempotencyKey_example // kotlin.String | Stable key so a replayed mutation is not applied twice.
            //apiInstance.apiV1DriveIdTrashPost(id, idempotencyKey)
        }

        // to test apiV1DriveUploadPost
        should("test apiV1DriveUploadPost") {
            // uncomment below to test apiV1DriveUploadPost
            //val file : java.io.File = BINARY_DATA_HERE // java.io.File | 
            //val idempotencyKey : kotlin.String = idempotencyKey_example // kotlin.String | Stable key so a replayed mutation is not applied twice.
            //val folderId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.apiV1DriveUploadPost(file, idempotencyKey, folderId)
        }

    }
}
