/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.apis.MeApi
import com.kubuno.api.models.RefreshToken
import com.kubuno.api.models.User

class MeApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MeApi
        //val apiInstance = MeApi()

        // to test getMe
        should("test getMe") {
            // uncomment below to test getMe
            //val result : User = apiInstance.getMe()
            //result shouldBe ("TODO")
        }

        // to test listSessions
        should("test listSessions") {
            // uncomment below to test listSessions
            //val result : kotlin.collections.List<RefreshToken> = apiInstance.listSessions()
            //result shouldBe ("TODO")
        }

    }
}
