/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.kubuno.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.kubuno.api.apis.PushApi
import com.kubuno.api.models.RegisterDeviceDto
import com.kubuno.api.models.SetPreferenceDto

class PushApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PushApi
        //val apiInstance = PushApi()

        // to test apiV1MePushDevicesIdDelete
        should("test apiV1MePushDevicesIdDelete") {
            // uncomment below to test apiV1MePushDevicesIdDelete
            //val id : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | 
            //apiInstance.apiV1MePushDevicesIdDelete(id)
        }

        // to test apiV1MePushDevicesPost
        should("test apiV1MePushDevicesPost") {
            // uncomment below to test apiV1MePushDevicesPost
            //val registerDeviceDto : RegisterDeviceDto =  // RegisterDeviceDto | 
            //apiInstance.apiV1MePushDevicesPost(registerDeviceDto)
        }

        // to test apiV1MePushPreferencesGet
        should("test apiV1MePushPreferencesGet") {
            // uncomment below to test apiV1MePushPreferencesGet
            //apiInstance.apiV1MePushPreferencesGet()
        }

        // to test apiV1MePushPreferencesPatch
        should("test apiV1MePushPreferencesPatch") {
            // uncomment below to test apiV1MePushPreferencesPatch
            //val setPreferenceDto : SetPreferenceDto =  // SetPreferenceDto | 
            //apiInstance.apiV1MePushPreferencesPatch(setPreferenceDto)
        }

    }
}
